version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run:
          name: Spin up Linux containers
          command: |
            docker run --rm busybox echo hello_world
            docker image ls

workflows:
  main:
    jobs:
      - test
